//! The language table: keywords, comment and string rules for each language.

use super::Lang;

const C_KEYWORDS: &[&str] = &[
    "auto", "break", "case", "const", "continue", "default", "do", "else", "enum", "extern", "for",
    "goto", "if", "inline", "register", "restrict", "return", "sizeof", "static", "struct",
    "switch", "typedef", "union", "volatile", "while", "NULL", "true", "false",
];
const C_TYPES: &[&str] = &[
    "char",
    "double",
    "float",
    "int",
    "long",
    "short",
    "signed",
    "unsigned",
    "void",
    "bool",
    "size_t",
    "ssize_t",
    "ptrdiff_t",
    "int8_t",
    "int16_t",
    "int32_t",
    "int64_t",
    "uint8_t",
    "uint16_t",
    "uint32_t",
    "uint64_t",
    "uintptr_t",
    "intptr_t",
    "FILE",
    "wchar_t",
];
const CPP_KEYWORDS: &[&str] = &[
    "alignas",
    "alignof",
    "auto",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "consteval",
    "constexpr",
    "constinit",
    "const_cast",
    "continue",
    "co_await",
    "co_return",
    "co_yield",
    "decltype",
    "default",
    "delete",
    "do",
    "dynamic_cast",
    "else",
    "enum",
    "explicit",
    "export",
    "extern",
    "false",
    "final",
    "for",
    "friend",
    "goto",
    "if",
    "inline",
    "mutable",
    "namespace",
    "new",
    "noexcept",
    "nullptr",
    "operator",
    "override",
    "private",
    "protected",
    "public",
    "reinterpret_cast",
    "requires",
    "return",
    "sizeof",
    "static",
    "static_assert",
    "static_cast",
    "struct",
    "switch",
    "template",
    "this",
    "throw",
    "true",
    "try",
    "typedef",
    "typename",
    "union",
    "using",
    "virtual",
    "volatile",
    "while",
    "concept",
];
const CPP_TYPES: &[&str] = &[
    "bool",
    "char",
    "char8_t",
    "char16_t",
    "char32_t",
    "double",
    "float",
    "int",
    "long",
    "short",
    "signed",
    "unsigned",
    "void",
    "wchar_t",
    "size_t",
    "int8_t",
    "int16_t",
    "int32_t",
    "int64_t",
    "uint8_t",
    "uint16_t",
    "uint32_t",
    "uint64_t",
    "std",
    "string",
    "vector",
    "map",
    "unordered_map",
    "unique_ptr",
    "shared_ptr",
    "optional",
    "array",
    "span",
    "string_view",
];

pub(super) static LANGS: &[Lang] = &[
    Lang {
        aliases: &["rs"],
        keywords: &[
            "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum",
            "extern", "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod",
            "move", "mut", "pub", "ref", "return", "self", "Self", "static", "struct", "super",
            "trait", "true", "type", "unsafe", "use", "where", "while", "yield",
        ],
        types: &[
            "i8", "i16", "i32", "i64", "i128", "isize", "u8", "u16", "u32", "u64", "u128", "usize",
            "f32", "f64", "bool", "char", "str",
        ],
        line_comments: &["//"],
        block_comment: Some(("/*", "*/")),
        char_literals: true,
        capitalized_types: true,
        bang_macros: true,
        ..Lang::base("rust")
    },
    Lang {
        aliases: &["py", "python3", "py3"],
        keywords: &[
            "False", "None", "True", "and", "as", "assert", "async", "await", "break", "case",
            "class", "continue", "def", "del", "elif", "else", "except", "finally", "for", "from",
            "global", "if", "import", "in", "is", "lambda", "match", "nonlocal", "not", "or",
            "pass", "raise", "return", "self", "try", "while", "with", "yield",
        ],
        types: &[
            "int",
            "float",
            "str",
            "bool",
            "bytes",
            "list",
            "dict",
            "set",
            "tuple",
            "object",
            "complex",
            "frozenset",
            "type",
        ],
        line_comments: &["#"],
        quotes: &['"', '\''],
        triple_quotes: true,
        capitalized_types: true,
        colon_blocks: true,
        ..Lang::base("python")
    },
    Lang {
        aliases: &["h"],
        keywords: C_KEYWORDS,
        types: C_TYPES,
        line_comments: &["//"],
        block_comment: Some(("/*", "*/")),
        quotes: &['"', '\''],
        preprocessor: true,
        ..Lang::base("c")
    },
    Lang {
        aliases: &["c++", "cc", "cxx", "hpp", "hh", "hxx"],
        keywords: CPP_KEYWORDS,
        types: CPP_TYPES,
        line_comments: &["//"],
        block_comment: Some(("/*", "*/")),
        quotes: &['"', '\''],
        preprocessor: true,
        capitalized_types: true,
        ..Lang::base("cpp")
    },
    Lang {
        aliases: &["cs", "c#"],
        keywords: &[
            "abstract",
            "as",
            "async",
            "await",
            "base",
            "break",
            "case",
            "catch",
            "checked",
            "class",
            "const",
            "continue",
            "default",
            "delegate",
            "do",
            "else",
            "enum",
            "event",
            "explicit",
            "extern",
            "false",
            "finally",
            "fixed",
            "for",
            "foreach",
            "get",
            "goto",
            "if",
            "implicit",
            "in",
            "interface",
            "internal",
            "is",
            "lock",
            "namespace",
            "new",
            "null",
            "operator",
            "out",
            "override",
            "params",
            "private",
            "protected",
            "public",
            "readonly",
            "record",
            "ref",
            "return",
            "sealed",
            "set",
            "sizeof",
            "static",
            "struct",
            "switch",
            "this",
            "throw",
            "true",
            "try",
            "typeof",
            "unsafe",
            "using",
            "var",
            "virtual",
            "void",
            "volatile",
            "while",
            "yield",
        ],
        types: &[
            "bool", "byte", "char", "decimal", "double", "float", "int", "long", "object", "sbyte",
            "short", "string", "uint", "ulong", "ushort", "dynamic",
        ],
        line_comments: &["//"],
        block_comment: Some(("/*", "*/")),
        quotes: &['"', '\''],
        preprocessor: true,
        capitalized_types: true,
        ..Lang::base("csharp")
    },
    Lang {
        aliases: &["kt", "kotlin"],
        keywords: &[
            "abstract",
            "assert",
            "break",
            "case",
            "catch",
            "class",
            "const",
            "continue",
            "default",
            "do",
            "else",
            "enum",
            "extends",
            "final",
            "finally",
            "for",
            "if",
            "implements",
            "import",
            "instanceof",
            "interface",
            "native",
            "new",
            "null",
            "package",
            "private",
            "protected",
            "public",
            "return",
            "static",
            "super",
            "switch",
            "synchronized",
            "this",
            "throw",
            "throws",
            "transient",
            "true",
            "false",
            "try",
            "var",
            "void",
            "volatile",
            "while",
            "record",
            "fun",
            "val",
            "when",
            "object",
            "is",
            "in",
        ],
        types: &[
            "boolean", "byte", "char", "double", "float", "int", "long", "short",
        ],
        line_comments: &["//"],
        block_comment: Some(("/*", "*/")),
        quotes: &['"', '\''],
        capitalized_types: true,
        ..Lang::base("java")
    },
    Lang {
        aliases: &["js", "jsx", "mjs", "cjs", "ts", "tsx", "typescript", "node"],
        keywords: &[
            "async",
            "await",
            "break",
            "case",
            "catch",
            "class",
            "const",
            "continue",
            "debugger",
            "default",
            "delete",
            "do",
            "else",
            "export",
            "extends",
            "false",
            "finally",
            "for",
            "from",
            "function",
            "if",
            "import",
            "in",
            "instanceof",
            "let",
            "new",
            "null",
            "of",
            "return",
            "static",
            "super",
            "switch",
            "this",
            "throw",
            "true",
            "try",
            "typeof",
            "undefined",
            "var",
            "void",
            "while",
            "with",
            "yield",
            "interface",
            "type",
            "enum",
            "implements",
            "private",
            "protected",
            "public",
            "readonly",
            "as",
            "declare",
            "namespace",
            "abstract",
        ],
        types: &[
            "string", "number", "boolean", "any", "unknown", "never", "object", "bigint", "symbol",
        ],
        line_comments: &["//"],
        block_comment: Some(("/*", "*/")),
        quotes: &['"', '\'', '`'],
        capitalized_types: true,
        ..Lang::base("javascript")
    },
    Lang {
        aliases: &["golang"],
        keywords: &[
            "break",
            "case",
            "chan",
            "const",
            "continue",
            "default",
            "defer",
            "else",
            "fallthrough",
            "for",
            "func",
            "go",
            "goto",
            "if",
            "import",
            "interface",
            "map",
            "package",
            "range",
            "return",
            "select",
            "struct",
            "switch",
            "type",
            "var",
            "true",
            "false",
            "nil",
            "iota",
        ],
        types: &[
            "bool",
            "byte",
            "complex64",
            "complex128",
            "error",
            "float32",
            "float64",
            "int",
            "int8",
            "int16",
            "int32",
            "int64",
            "rune",
            "string",
            "uint",
            "uint8",
            "uint16",
            "uint32",
            "uint64",
            "uintptr",
            "any",
        ],
        line_comments: &["//"],
        block_comment: Some(("/*", "*/")),
        quotes: &['"', '\'', '`'],
        tab_indent: true,
        ..Lang::base("go")
    },
    Lang {
        aliases: &["hlsl", "vert", "frag", "wgsl", "shader"],
        keywords: &[
            "break",
            "case",
            "const",
            "continue",
            "default",
            "discard",
            "do",
            "else",
            "for",
            "if",
            "in",
            "inout",
            "out",
            "return",
            "struct",
            "switch",
            "uniform",
            "varying",
            "attribute",
            "layout",
            "precision",
            "highp",
            "mediump",
            "lowp",
            "while",
            "true",
            "false",
            "fn",
            "let",
            "var",
            "cbuffer",
            "register",
        ],
        types: &[
            "void",
            "bool",
            "int",
            "uint",
            "float",
            "double",
            "vec2",
            "vec3",
            "vec4",
            "ivec2",
            "ivec3",
            "ivec4",
            "uvec2",
            "uvec3",
            "uvec4",
            "mat2",
            "mat3",
            "mat4",
            "sampler2D",
            "samplerCube",
            "float2",
            "float3",
            "float4",
            "float4x4",
            "half",
            "Texture2D",
            "SamplerState",
            "f32",
            "i32",
            "u32",
        ],
        line_comments: &["//"],
        block_comment: Some(("/*", "*/")),
        preprocessor: true,
        ..Lang::base("glsl")
    },
    Lang {
        aliases: &["jsonc", "json5"],
        keywords: &["true", "false", "null"],
        line_comments: &["//"],
        block_comment: Some(("/*", "*/")),
        keys: true,
        ..Lang::base("json")
    },
    Lang {
        aliases: &["ini", "cfg", "conf"],
        keywords: &["true", "false"],
        line_comments: &["#", ";"],
        quotes: &['"', '\''],
        triple_quotes: true,
        keys: true,
        ..Lang::base("toml")
    },
    Lang {
        aliases: &["yml"],
        keywords: &["true", "false", "null", "yes", "no", "on", "off"],
        line_comments: &["#"],
        quotes: &['"', '\''],
        keys: true,
        colon_blocks: true,
        ..Lang::base("yaml")
    },
    Lang {
        aliases: &["sh", "shell", "zsh", "console", "shellscript", "fish"],
        keywords: &[
            "if", "then", "else", "elif", "fi", "for", "while", "until", "do", "done", "case",
            "esac", "in", "function", "return", "local", "export", "readonly", "declare", "source",
            "alias", "set", "unset", "shift", "exit", "break", "continue", "echo", "cd", "sudo",
        ],
        line_comments: &["#"],
        quotes: &['"', '\''],
        dollar_vars: true,
        ..Lang::base("bash")
    },
    Lang {
        aliases: &["ps1", "ps", "pwsh"],
        keywords: &[
            "begin",
            "break",
            "catch",
            "class",
            "continue",
            "data",
            "do",
            "dynamicparam",
            "else",
            "elseif",
            "end",
            "exit",
            "filter",
            "finally",
            "for",
            "foreach",
            "from",
            "function",
            "if",
            "in",
            "param",
            "process",
            "return",
            "switch",
            "throw",
            "trap",
            "try",
            "until",
            "using",
            "var",
            "while",
            "true",
            "false",
            "null",
        ],
        line_comments: &["#"],
        block_comment: Some(("<#", "#>")),
        quotes: &['"', '\''],
        dollar_vars: true,
        case_insensitive: true,
        ..Lang::base("powershell")
    },
    Lang {
        aliases: &["bat", "cmd"],
        keywords: &[
            "echo",
            "set",
            "if",
            "else",
            "for",
            "in",
            "do",
            "goto",
            "call",
            "exit",
            "not",
            "exist",
            "defined",
            "errorlevel",
            "setlocal",
            "endlocal",
            "rem",
            "pause",
            "shift",
        ],
        line_comments: &["::", "rem ", "REM "],
        case_insensitive: true,
        ..Lang::base("batch")
    },
    Lang {
        aliases: &["mysql", "postgres", "postgresql", "sqlite", "psql", "plsql"],
        keywords: &[
            "select",
            "from",
            "where",
            "and",
            "or",
            "not",
            "insert",
            "into",
            "values",
            "update",
            "set",
            "delete",
            "create",
            "table",
            "drop",
            "alter",
            "add",
            "column",
            "index",
            "on",
            "join",
            "left",
            "right",
            "inner",
            "outer",
            "full",
            "cross",
            "group",
            "by",
            "order",
            "having",
            "limit",
            "offset",
            "as",
            "distinct",
            "union",
            "all",
            "in",
            "is",
            "null",
            "like",
            "between",
            "exists",
            "case",
            "when",
            "then",
            "else",
            "end",
            "primary",
            "key",
            "foreign",
            "references",
            "default",
            "unique",
            "view",
            "with",
            "returning",
            "begin",
            "commit",
            "rollback",
            "transaction",
            "asc",
            "desc",
            "true",
            "false",
            "if",
            "count",
            "sum",
            "avg",
            "min",
            "max",
        ],
        types: &[
            "int",
            "integer",
            "bigint",
            "smallint",
            "text",
            "varchar",
            "char",
            "boolean",
            "date",
            "timestamp",
            "real",
            "float",
            "double",
            "decimal",
            "numeric",
            "blob",
            "serial",
            "uuid",
            "json",
            "jsonb",
        ],
        line_comments: &["--", "#"],
        block_comment: Some(("/*", "*/")),
        quotes: &['\'', '"', '`'],
        case_insensitive: true,
        ..Lang::base("sql")
    },
    Lang {
        aliases: &["xml", "htm", "xhtml", "svg", "vue", "svelte"],
        block_comment: Some(("<!--", "-->")),
        quotes: &['"', '\''],
        tags: true,
        ..Lang::base("html")
    },
    Lang {
        aliases: &["scss", "sass", "less"],
        keywords: &["!important", "inherit", "initial", "unset", "none", "auto"],
        line_comments: &[],
        block_comment: Some(("/*", "*/")),
        quotes: &['"', '\''],
        keys: true,
        ..Lang::base("css")
    },
    Lang {
        aliases: &["luau"],
        keywords: &[
            "and", "break", "do", "else", "elseif", "end", "false", "for", "function", "goto",
            "if", "in", "local", "nil", "not", "or", "repeat", "return", "then", "true", "until",
            "while", "self",
        ],
        block_comment: Some(("--[[", "]]")),
        line_comments: &["--"],
        quotes: &['"', '\''],
        ..Lang::base("lua")
    },
    Lang {
        aliases: &["asm", "nasm", "masm", "x86", "x86asm", "s", "gas", "x64"],
        keywords: &[
            "section", "segment", "global", "extern", "db", "dw", "dd", "dq", "resb", "resw",
            "resd", "resq", "equ", "times", "proc", "endp", "end", "byte", "word", "dword",
            "qword", "ptr", "include", "macro", "endm", "bits", "default", "rel",
        ],
        line_comments: &[";", "#", "//"],
        quotes: &['"', '\''],
        case_insensitive: true,
        first_word_keyword: true,
        ..Lang::base("assembly")
    },
    Lang {
        aliases: &["makefile", "mk"],
        keywords: &[
            "ifeq", "ifneq", "ifdef", "ifndef", "else", "endif", "include", "define", "endef",
            "export", "override", ".PHONY",
        ],
        line_comments: &["#"],
        quotes: &['"', '\''],
        dollar_vars: true,
        tab_indent: true,
        ..Lang::base("make")
    },
];

/// Assembly registers, colored as types.
pub(super) fn is_register(word: &str) -> bool {
    const REGS: &[&str] = &[
        "rax", "rbx", "rcx", "rdx", "rsi", "rdi", "rbp", "rsp", "rip", "eax", "ebx", "ecx", "edx",
        "esi", "edi", "ebp", "esp", "eip", "ax", "bx", "cx", "dx", "si", "di", "bp", "sp", "al",
        "ah", "bl", "bh", "cl", "ch", "dl", "dh", "sil", "dil", "cs", "ds", "es", "fs", "gs", "ss",
    ];
    let w = word.to_ascii_lowercase();
    if REGS.contains(&w.as_str()) {
        return true;
    }
    // r8..r15 with an optional d/w/b suffix, and the SIMD registers.
    let numbered = |prefix: &str| {
        w.strip_prefix(prefix).is_some_and(|rest| {
            let digits = rest.trim_end_matches(['d', 'w', 'b']);
            !digits.is_empty() && digits.bytes().all(|b| b.is_ascii_digit())
        })
    };
    numbered("r") || numbered("xmm") || numbered("ymm") || numbered("zmm")
}
